---
- name: make sure apt cache is up to date 
  apt: update_cache=yes upgrade=full

- name: create the build server user (in shadow for supervisord)
  user: name={{ builder }} shell=/bin/bash home={{ builder_home }} append=yes groups=shadow

- name: make sources directory for builder user 
  file: state=directory path={{ builder_home }}/.sources

- name: add bashrc that sources go to builder
  template: src=bashrc.j2 dest={{ builder_home }}/.bashrc owner={{ builder }} group={{ builder_group }} mode=0600

- name: add bash profile that sources bashrc 
  template: src=bash_profile.j2 dest={{ builder_home }}/.bash_profile owner={{ builder }} group={{ builder_group }} mode=0600
