---
- name: Download latest grimd
  get_url: url={{ grimd_download_url }} url_username={{ artifactory_user }} url_password={{ artifactory_password }} dest={{ grimd_download_location }}
  register: grim_downloaded

- name: Install zip
  apt: pkg=zip state=present

- name: Install grimd
  unarchive: copy=no dest={{ grimd_install_location }} src={{ grim_downloaded.dest }}

- name: create log directory
  file: state=directory path=/var/log/grim owner={{ builder }} group={{ builder_group }} mode=0770

- name: create scratch directory 
  file: state=directory path=/var/tmp/grim owner={{ builder }} group={{ builder_group }} mode=0770

- name: create config directory
  file: state=directory path=/etc/grim owner={{ builder }} group={{ builder_group }} mode=0770

- name: install grimd systemd service unit
  template: src=grimd.service.j2 dest=/etc/systemd/system/grimd.service
  sudo: yes

- name: make sure grimd is enabled
  service: name=grimd enabled=yes
  sudo: yes
